#define IDL_BARR_INI_NOP BASICARR_INI_NOP
#define IDL_BARR_INI_ZERO BASICARR_INI_ZERO
#define IDL_CHARA CHARA
#define IDL_COMPLEX COMPLEX
#define IDL_DELTMP DELTMP
#define IDL_KW_CLEAN_ALL KW_CLEAN_ALL
#define IDL_KW_PAR KW_PAR
#define IDL_KW_ZERO KW_ZERO
#define IDL_LONG LONG
#define IDL_MessageErrno message
#define IDL_MSG_LONGJMP MSG_LONGJMP
#define IDL_M_NAMED_GENERIC M_NAMED_GENERIC
#define IDL_STRING STRING
#define IDL_STRING_STR STRING_STR
#define IDL_TYP_BYTE TYP_BYTE
#define IDL_TYP_COMPLEX TYP_COMPLEX
#define IDL_TYP_DOUBLE TYP_DOUBLE
#define IDL_TYP_FLOAT TYP_FLOAT
#define IDL_TYP_INT TYP_INT
#define IDL_TYP_LONG TYP_LONG
#define IDL_TYP_STRING TYP_STRING
#define IDL_UCHAR UCHAR
#define IDL_ULONG ULONG
#define IDL_VARIABLE VARIABLE
#define IDL_V_NOT_SCALAR V_NOT_SCALAR
#define IDL_VPTR VPTR

#define IDL_Gettmp gettmp
#define IDL_KWGetParams get_kw_params
#define IDL_KWCleanup keyword_cleanup
#define IDL_MakeTempArray make_temp_array
#define IDL_StrStore str_store
#define IDL_VarCopy var_copy

#define IDL_KW_ARGS KW_ARGS
#define IDL_SYSFUN_DEF SYSFUN_DEF
#define IDL_FUN_RET FUN_RET
#define IDL_MSG_INFO MSG_INFO
#define IDL_AddSystemRoutine add_system_routine
